server:
  port: 8888
spring:
  redis:
    host: 192.168.11.30
    port: 6379
    password: Aa123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 1
  application:
    name: seckill
  datasource.:
    url: jdbc:mysql://192.168.3.90:23306/db1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: mycat
    password: A123456a!
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 500
    initialSize: 100
    maxWait: 500
    minIdle: 0
    maxIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  rabbitmq:
    host: 192.168.11.30
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.0
# mybatis
mybatis:
  type-aliases-package: com.llspace.seckill.entity
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
  before: false
  not-empty: true
#static
resources:
  add-mappings: true
  cache-period: 3600
  static-locations: classpath:/static/
  chain:
    cache: true
    enabled: true
    gzipped: true
    html-application-cache: true
#启动时控制台打印生效的API信息
logging:
  level:
    org.springframework.web: TRACE

